### ISSUE TITLE
Borg files

### ISSUE THREAD

**Issue by rounak-meyur** [kravitsjacob/mocot#23]
I was trying to execute the Multi-objective optimization on Unix system using the instructions provided in the README.md file. It mentions about placing "borg" files in a directory. However, I am confused where to get these files. Can you provide an example, or point me about how to create these files.

**Comment by kravitsjacob** [comment]
Hello, 

I hope you are well. [Borg](http://borgmoea.org/) is a multi-objective evolutionary algorithm. I used it for generating the set of nondominated solutions to my multi-objective problem. It has a free non-commercial and academic license that you can get [here](http://borgmoea.org/#download). After you download just place the source files in that folder and all the referencing should be handled for you!
